language: ruby
rvm:
 - 2.2.2
# - jruby
# - rbx-2

before_script:
  - psql -c 'create database database_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
 

 
services:
  - postgresql